language: bash
services: docker

env:
  - VERSION=19.03 SUITE=sid ARCH=amd64

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$SUITE/$ARCH"
  - image="vicamo/docker:$VERSION-$SUITE-$ARCH"
  - if [ "$ARCH" != "amd64" ]; then
      docker run --rm --privileged vicamo/binfmt-qemu:bionic;
      cat /proc/sys/fs/binfmt_misc/qemu-*;
    fi

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - travis_retry docker build -t "$image-dind" dind
  - ~/official-images/test/run.sh "$image-dind"
  - travis_retry docker build -t "$image-git" git
  - ~/official-images/test/run.sh "$image-git"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
